### ISSUE TITLE
Status "Fahrzeug verschlossen" aktualisiert sich nicht

### ISSUE THREAD

**Issue by dominikkerkow** [TA2k/ioBroker.porsche#1]
Das Thema UNLOCK oder LOCK funktioniert nicht. Wenn ich das Auto nicht verschlossen habe, dann bekomme ich keinen veränderten Status (Wartezeit weit über 10 Minuten). Kannst Du bitte einmal prüfen, ob Du hier etwas tun kannst, als nur die Status abzurufen?

**Comment by TA2k** [comment]
Ich bin unsicher ob der Status gegeben wird. Denn in der App sehe ich den Status auch nicht oder?

**Comment by dominikkerkow** [comment]
Da hast Du Recht. In der Connect App sehe ich den Status.

**Comment by TA2k** [comment]
Schade sollte man mal anfragen wann das in die My App übertragen wird

**Comment by dominikkerkow** [comment]
Eben getestet, die MyPorsche App zeigt oben links kurz ein Symbol mit geöffnetem Schloss an, dort wo sonst das Fahrzeug Icon mit grünem Haken ist.

**Comment by TA2k** [comment]
Hast du ein screenshot?

**Comment by dominikkerkow** [comment]
Versuche ich, ist leider nur kurz da. Wenn Du dann oben auf das Fahrzeug Icon mit dem Haken gehst, dann siehst Du einen weiteren Screen mit Infos. Dort steht dann nur kurzfristig, dass das Auto offen ist. Danach steht geschlossen, obwohl dies nicht der Fall ist!
Wie kann ich hier Bilder hochladen?

**Comment by dominikkerkow** [comment]
Habe die Bilder eben per Mail gesendet

**Comment by TA2k** [comment]
porsche.0.VIN.status.LOCK_STATE_VEHICLE.value.isLocked

Da ist es zu finden

**Comment by dominikkerkow** [comment]
Danke, ich teste dies ausführlich.
